FROM hashicorp/terraform:0.12.29

# Add common dependencies
RUN apk update && \
    apk add openssl curl tar gzip bash ca-certificates coreutils

# Add Azure CLI
RUN \
    apk add py3-pip && \
    apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python3-dev make && \
    pip3 --no-cache-dir install -U pip && \
    pip3 --no-cache-dir install azure-cli && \
    apk del --purge build
