language: go

go:
- 1.11.x
- master

go_import_path: github.com/NathanielRose/bedrock

before_install:
- cp .netrc ~/.netrc
- chmod 600 ~/.netrc

script: go test -v  ./... -timeout 99999s




