on:
  push:
    branches:
      - main
      - master
  
  pull_request:
    branches:
      - main
      - master

jobs:
  FabrikateToManifest:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Bedrock orchestration script
        run: |
          curl $BEDROCK_BUILD_SCRIPT > build.sh
          chmod +x ./build.sh
        shell: bash
        env:
          BEDROCK_BUILD_SCRIPT: https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh

  
      - uses: azure/setup-helm@v1
        with:
          version: '2.17.0' # default is latest stable
        id: install

      - name: Validate fabrikate definitions
        run: |
          chmod +x ./build.sh
          ./build.sh
        shell: bash
        env:
          MAJOR: 1
          VERIFY_ONLY: 1

      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch_name

      - name: Transform fabrikate definitions and publish to YAML manifests to repo
        run: |
          ./build.sh
        shell: bash
        env:
          MAJOR: 1
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          REPO: ${{ secrets.MANIFEST_REPO }}
          BRANCH_NAME: ${{ steps.get_branch_name.outputs.branch_name }}
