#!/bin/bash

mkdir -p deployments/$1
cd deployments/$1

REPO_URL=$REPO_ROOT/$REPO_NAME
echo "cloning $REPO_URL"

rm -rf $REPO_NAME

if ! git clone $REPO_URL; then
    echo "ERROR: failed to clone $REPO_URL"
    exit 1
fi

cd $REPO_NAME

DATE_TAG=`date -u +"%Y%m%dT%H%M%SZ"`
RELEASE_TAG=$CONTAINER_REPO/$SERVICE_NAME:$DATE_TAG

if ! docker build -t $RELEASE_TAG .; then
    echo "ERROR: failed to docker build"
    exit 1
fi

if ! docker push $RELEASE_TAG; then
    echo "ERROR: failed to docker push"
    exit 1
fi

if ! helm upgrade $SERVICE_NAME --install --namespace $NAMESPACE --set image=$RELEASE_TAG --values=$VALUES_FILE --wait devops; then
    echo "ERROR: failed to helm upgrade --install"
    exit 1
fi

cd ../..
